package com.myfirstproject.Day06;

import org.junit.Assert;
import org.junit.Test;
import org.openqa.selenium.By;
import personal_practice.TestBase;

public class Alerts extends TestBase {
    /*
            Q: what is Alert
    Alert is a pop up that is generated by JS
    Alerts are used to yo give informational messages
    when there is an alert pop up on th page ,we must handel the alert otherwise we can not continue TO THE TEST EXECUTION
            Q: how do we handle Alert
      First of all we can not inspect JS Alerts,
   switch to alert then
   use accept to click OK,
   dismiss to click Cancel,
   getText to get the text,
   and sendKeys to type a text on the alert
     */

    @Test
public void acceptAlert(){

     /*
     homerwork 1
     acceptAlert() --> click on the first alert
     verify the text " I am a JS Alert"
     click OK,
     and verify "You successfully clicked an alert"
      */


    }
    @Test
    public void dismissAlert(){
        /*
     homerwork 2
     dismissAlert() --> click on the second alert
     verify the text " I am a JS Confirm"
     click OK,
     and verify "You clicked : Cancel"
      */
    }


    @Test
    public void sendKeysAlert(){
/*
     homerwork 1
     acceptAlert() --> click on the third alert
     verify the text " I am a JS prompt"
     type "Hello World"
     click OK,
     and verify "You entered : Hello World"
     collapse
      */
  driver.get("https://testcenter.techproeducation.com/index.php?page=javascript-alerts");
  //click on the third alert
 driver.findElement(By.xpath("//button[@onclick='jsPrompt()']")).click();
//  verify the text " I am a JS prompt"    that text is not a HTML content we an not inspect by right click
          String actualAlertText=driver.switchTo().alert().getText();
        Assert.assertEquals("I am a JS prompt",actualAlertText);
        // type "Hello World"
        driver.switchTo().alert().sendKeys("Hello World");
   //click ok
        driver.switchTo().alert().accept();
      //  and verify "You entered : Hello World"   -->  this is an HTML content  this is the result on the screen  not on the popup
   String actualResultText=driver.findElement(By.id("result")).getText();
  Assert.assertEquals("You entered : Hello World",actualResultText);

    }

}
